# Generated by Django 4.2.1 on 2023-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date_envoie',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
