# Generated by Django 4.2.1 on 2023-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_date_envoie'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
