# Generated by Django 4.2.1 on 2023-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_alter_membres_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
