# Generated by Django 4.2.1 on 2023-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_alter_membres_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
