# Generated by Django 4.2.1 on 2023-06-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_remove_membres_price_membres_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='adresse',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
