# Generated by Django 4.2.1 on 2023-06-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0006_membres_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membres',
            name='user',
        ),
    ]
