# Generated by Django 4.2.4 on 2023-08-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0007_remove_membres_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
