# Generated by Django 4.2.1 on 2023-05-10 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_utilisateur_email_alter_utilisateur_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(error_messages={'invalid': 'Veuillez entrer un numéro de téléphone valide.', 'required': 'Ce champ est obligatoire.'}, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{0,15}(?:\\s\\d{0,15})?$')]),
        ),
    ]
