# Generated by Django 4.2.1 on 2023-05-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_utilisateur_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
