# Generated by Django 4.2.1 on 2023-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_usercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercounter',
            name='value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
