# Generated by Django 4.2.1 on 2023-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_usercounter_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='budget',
            new_name='inscription',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='investisseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='usercounter',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
