# Generated by Django 4.2.1 on 2023-05-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_rename_budget_utilisateur_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='frais_inscription_investisseur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
