# Generated by Django 4.2.1 on 2023-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_utilisateur_frais_inscription_investisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='frais_inscription_investisseur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='inscription',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
