# Generated by Django 4.2.1 on 2023-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_alter_utilisateur_frais_inscription_investisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='frais_inscription_investisseur',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='inscription',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
