# Generated by Django 4.2.1 on 2023-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_alter_utilisateur_frais_inscription_investisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
