# Generated by Django 4.2.1 on 2023-06-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='prenom',
            field=models.CharField(default='Pangou', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('inscription', 'Inscription'), ('contact', 'Contact'), ('retrait', 'Demande de retrait'), ('investisssement', 'Investiseement')], max_length=50),
        ),
    ]
