# Generated by Django 4.2.1 on 2023-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_notification_prenom_alter_notification_type_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('inscription', 'Inscription'), ('retrait', 'Demande de retrait'), ('investissement', 'Investissement')], max_length=50),
        ),
    ]
