# Generated by Django 4.2.1 on 2023-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_alter_notification_type_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='matricule',
            field=models.CharField(default='rien', max_length=50),
            preserve_default=False,
        ),
    ]
