# Generated by Django 4.2.1 on 2023-07-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_notification_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='frais_inscription_investisseur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='solde',
        ),
    ]
