# Generated by Django 4.2.4 on 2023-08-23 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0018_remove_utilisateur_frais_inscription_investisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Entre une adresse mail valide.')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(error_messages={'invalid': 'Votre numéro de téléphone ne doit pas contenir des espaces.', 'required': 'Ce champ est obligatoire.'}, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format '+33612345678'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
