# Generated by Django 4.2.4 on 2023-08-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0019_alter_utilisateur_adresse_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='inscription',
        ),
    ]
