# Generated by Django 4.2.1 on 2023-06-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_investissement', models.CharField(max_length=50, unique=True, verbose_name='Niveau')),
                ('montant_min', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_max', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('montant_investi', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('revenue_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('total_de_gains', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('retrait_en_attente', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('total_de_retrait', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('date_inscris', models.DateTimeField(auto_now_add=True, null=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investisseurs.investissement')),
                ('solde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solde_investisseur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investisseur',
                'verbose_name_plural': 'Investisseurs',
            },
        ),
    ]
