# Generated by Django 4.2.1 on 2023-06-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investisseurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investisseur',
            name='solde',
        ),
    ]
