# Generated by Django 4.2.1 on 2023-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseurs', '0002_remove_investisseur_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
