# Generated by Django 4.2.1 on 2023-06-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseurs', '0004_alter_investisseur_montant_investi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investisseur',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='investisseur',
            name='lastname',
        ),
        migrations.AddField(
            model_name='investisseur',
            name='nom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investisseur',
            name='prenom',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
