# Generated by Django 4.2.1 on 2023-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseurs', '0005_remove_investisseur_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='status_retrait',
            field=models.CharField(choices=[('approuvé', 'Approuvé'), ('attente', 'Attente'), ('rejeté', 'rejeté'), ('aucun', 'aucun')], default='aucun', max_length=50),
        ),
    ]
