# Generated by Django 4.2.1 on 2023-07-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseurs', '0007_investisseur_date_augmentation_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='date_inscris',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
